// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var iroha = iroha || {};

/**
 *//////////////////////////////////
 *
 * @enum
 */
iroha.ProgrammingLanguage = {
  Java8: 0
};

/**
 * @enum
 */
iroha.UserPermission = {
  NONE: 0,
  UserPermissionRoot: 1,
  UserPermissionLedger: 2,
  UserPermissionDomain: 3,
  UserPermissionAsset: 4
};

/**
 * @constructor
 */
iroha.Chaincode = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {iroha.Chaincode}
 */
iroha.Chaincode.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {iroha.Chaincode=} obj
 * @returns {iroha.Chaincode}
 */
iroha.Chaincode.getRootAsChaincode = function(bb, obj) {
  return (obj || new iroha.Chaincode).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
iroha.Chaincode.prototype.codeName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
iroha.Chaincode.prototype.domainName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
iroha.Chaincode.prototype.ledgerName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {iroha.ProgrammingLanguage}
 */
iroha.Chaincode.prototype.language = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? /** @type {iroha.ProgrammingLanguage} */ (this.bb.readUint8(this.bb_pos + offset)) : iroha.ProgrammingLanguage.Java8;
};

/**
 * @param {number} index
 * @returns {number}
 */
iroha.Chaincode.prototype.code = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns {number}
 */
iroha.Chaincode.prototype.codeLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint8Array}
 */
iroha.Chaincode.prototype.codeArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
iroha.Chaincode.startChaincode = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} codeNameOffset
 */
iroha.Chaincode.addCodeName = function(builder, codeNameOffset) {
  builder.addFieldOffset(0, codeNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} domainNameOffset
 */
iroha.Chaincode.addDomainName = function(builder, domainNameOffset) {
  builder.addFieldOffset(1, domainNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} ledgerNameOffset
 */
iroha.Chaincode.addLedgerName = function(builder, ledgerNameOffset) {
  builder.addFieldOffset(2, ledgerNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {iroha.ProgrammingLanguage} language
 */
iroha.Chaincode.addLanguage = function(builder, language) {
  builder.addFieldInt8(3, language, iroha.ProgrammingLanguage.Java8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} codeOffset
 */
iroha.Chaincode.addCode = function(builder, codeOffset) {
  builder.addFieldOffset(4, codeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
iroha.Chaincode.createCodeVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
iroha.Chaincode.startCodeVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
iroha.Chaincode.endChaincode = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // code_name
  builder.requiredField(offset, 6); // domain_name
  builder.requiredField(offset, 8); // ledger_name
  return offset;
};

/**
 *//////////////////////////////////
 * Key-Value object
 *
 * @constructor
 */
iroha.KeyValueObject = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {iroha.KeyValueObject}
 */
iroha.KeyValueObject.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {iroha.KeyValueObject=} obj
 * @returns {iroha.KeyValueObject}
 */
iroha.KeyValueObject.getRootAsKeyValueObject = function(bb, obj) {
  return (obj || new iroha.KeyValueObject).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
iroha.KeyValueObject.prototype.key = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @returns {number}
 */
iroha.KeyValueObject.prototype.value = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns {number}
 */
iroha.KeyValueObject.prototype.valueLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint8Array}
 */
iroha.KeyValueObject.prototype.valueArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
iroha.KeyValueObject.startKeyValueObject = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} keyOffset
 */
iroha.KeyValueObject.addKey = function(builder, keyOffset) {
  builder.addFieldOffset(0, keyOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} valueOffset
 */
iroha.KeyValueObject.addValue = function(builder, valueOffset) {
  builder.addFieldOffset(1, valueOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
iroha.KeyValueObject.createValueVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
iroha.KeyValueObject.startValueVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
iroha.KeyValueObject.endKeyValueObject = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // key
  return offset;
};

/**
 *//////////////////////////////////
 * Permissions
 *
 * @constructor
 */
iroha.UserPermissionRoot = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {iroha.UserPermissionRoot}
 */
iroha.UserPermissionRoot.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {iroha.UserPermissionRoot=} obj
 * @returns {iroha.UserPermissionRoot}
 */
iroha.UserPermissionRoot.getRootAsUserPermissionRoot = function(bb, obj) {
  return (obj || new iroha.UserPermissionRoot).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionRoot.prototype.ledgerAdd = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionRoot.prototype.ledgerRemove = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
iroha.UserPermissionRoot.startUserPermissionRoot = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} ledgerAdd
 */
iroha.UserPermissionRoot.addLedgerAdd = function(builder, ledgerAdd) {
  builder.addFieldInt8(0, +ledgerAdd, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} ledgerRemove
 */
iroha.UserPermissionRoot.addLedgerRemove = function(builder, ledgerRemove) {
  builder.addFieldInt8(1, +ledgerRemove, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
iroha.UserPermissionRoot.endUserPermissionRoot = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
iroha.UserPermissionLedger = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {iroha.UserPermissionLedger}
 */
iroha.UserPermissionLedger.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {iroha.UserPermissionLedger=} obj
 * @returns {iroha.UserPermissionLedger}
 */
iroha.UserPermissionLedger.getRootAsUserPermissionLedger = function(bb, obj) {
  return (obj || new iroha.UserPermissionLedger).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
iroha.UserPermissionLedger.prototype.ledgerName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionLedger.prototype.domainAdd = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionLedger.prototype.domainRemove = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionLedger.prototype.peerAdd = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionLedger.prototype.peerRemove = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionLedger.prototype.userAdd = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionLedger.prototype.userRemove = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionLedger.prototype.userGivePermission = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
iroha.UserPermissionLedger.startUserPermissionLedger = function(builder) {
  builder.startObject(8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} ledgerNameOffset
 */
iroha.UserPermissionLedger.addLedgerName = function(builder, ledgerNameOffset) {
  builder.addFieldOffset(0, ledgerNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} domainAdd
 */
iroha.UserPermissionLedger.addDomainAdd = function(builder, domainAdd) {
  builder.addFieldInt8(1, +domainAdd, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} domainRemove
 */
iroha.UserPermissionLedger.addDomainRemove = function(builder, domainRemove) {
  builder.addFieldInt8(2, +domainRemove, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} peerAdd
 */
iroha.UserPermissionLedger.addPeerAdd = function(builder, peerAdd) {
  builder.addFieldInt8(3, +peerAdd, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} peerRemove
 */
iroha.UserPermissionLedger.addPeerRemove = function(builder, peerRemove) {
  builder.addFieldInt8(4, +peerRemove, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} userAdd
 */
iroha.UserPermissionLedger.addUserAdd = function(builder, userAdd) {
  builder.addFieldInt8(5, +userAdd, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} userRemove
 */
iroha.UserPermissionLedger.addUserRemove = function(builder, userRemove) {
  builder.addFieldInt8(6, +userRemove, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} userGivePermission
 */
iroha.UserPermissionLedger.addUserGivePermission = function(builder, userGivePermission) {
  builder.addFieldInt8(7, +userGivePermission, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
iroha.UserPermissionLedger.endUserPermissionLedger = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // ledger_name
  return offset;
};

/**
 * @constructor
 */
iroha.UserPermissionDomain = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {iroha.UserPermissionDomain}
 */
iroha.UserPermissionDomain.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {iroha.UserPermissionDomain=} obj
 * @returns {iroha.UserPermissionDomain}
 */
iroha.UserPermissionDomain.getRootAsUserPermissionDomain = function(bb, obj) {
  return (obj || new iroha.UserPermissionDomain).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
iroha.UserPermissionDomain.prototype.domainName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
iroha.UserPermissionDomain.prototype.ledgerName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionDomain.prototype.userGivePermission = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionDomain.prototype.userAdd = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionDomain.prototype.userRemove = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
iroha.UserPermissionDomain.startUserPermissionDomain = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} domainNameOffset
 */
iroha.UserPermissionDomain.addDomainName = function(builder, domainNameOffset) {
  builder.addFieldOffset(0, domainNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} ledgerNameOffset
 */
iroha.UserPermissionDomain.addLedgerName = function(builder, ledgerNameOffset) {
  builder.addFieldOffset(1, ledgerNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} userGivePermission
 */
iroha.UserPermissionDomain.addUserGivePermission = function(builder, userGivePermission) {
  builder.addFieldInt8(2, +userGivePermission, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} userAdd
 */
iroha.UserPermissionDomain.addUserAdd = function(builder, userAdd) {
  builder.addFieldInt8(3, +userAdd, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} userRemove
 */
iroha.UserPermissionDomain.addUserRemove = function(builder, userRemove) {
  builder.addFieldInt8(4, +userRemove, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
iroha.UserPermissionDomain.endUserPermissionDomain = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // domain_name
  builder.requiredField(offset, 6); // ledger_name
  return offset;
};

/**
 * @constructor
 */
iroha.UserPermissionAsset = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {iroha.UserPermissionAsset}
 */
iroha.UserPermissionAsset.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {iroha.UserPermissionAsset=} obj
 * @returns {iroha.UserPermissionAsset}
 */
iroha.UserPermissionAsset.getRootAsUserPermissionAsset = function(bb, obj) {
  return (obj || new iroha.UserPermissionAsset).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
iroha.UserPermissionAsset.prototype.assetName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
iroha.UserPermissionAsset.prototype.domainName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
iroha.UserPermissionAsset.prototype.ledgerName = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionAsset.prototype.transfer = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionAsset.prototype.add = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionAsset.prototype.remove = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
iroha.UserPermissionAsset.prototype.create = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
iroha.UserPermissionAsset.startUserPermissionAsset = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} assetNameOffset
 */
iroha.UserPermissionAsset.addAssetName = function(builder, assetNameOffset) {
  builder.addFieldOffset(0, assetNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} domainNameOffset
 */
iroha.UserPermissionAsset.addDomainName = function(builder, domainNameOffset) {
  builder.addFieldOffset(1, domainNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} ledgerNameOffset
 */
iroha.UserPermissionAsset.addLedgerName = function(builder, ledgerNameOffset) {
  builder.addFieldOffset(2, ledgerNameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} transfer
 */
iroha.UserPermissionAsset.addTransfer = function(builder, transfer) {
  builder.addFieldInt8(3, +transfer, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} add
 */
iroha.UserPermissionAsset.addAdd = function(builder, add) {
  builder.addFieldInt8(4, +add, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} remove
 */
iroha.UserPermissionAsset.addRemove = function(builder, remove) {
  builder.addFieldInt8(5, +remove, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} create
 */
iroha.UserPermissionAsset.addCreate = function(builder, create) {
  builder.addFieldInt8(6, +create, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
iroha.UserPermissionAsset.endUserPermissionAsset = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // asset_name
  builder.requiredField(offset, 6); // domain_name
  builder.requiredField(offset, 8); // ledger_name
  return offset;
};

/**
 *//////////////////////////////////
 * Peer
 *
 * @constructor
 */
iroha.Peer = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {iroha.Peer}
 */
iroha.Peer.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {iroha.Peer=} obj
 * @returns {iroha.Peer}
 */
iroha.Peer.getRootAsPeer = function(bb, obj) {
  return (obj || new iroha.Peer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {iroha.PublicKey=} obj
 * @returns {iroha.PublicKey}
 */
iroha.Peer.prototype.publicKey = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new iroha.PublicKey).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
iroha.Peer.prototype.ip = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
iroha.Peer.prototype.trust = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {boolean}
 */
iroha.Peer.prototype.active = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
iroha.Peer.prototype.joinNetwork = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns {boolean}
 */
iroha.Peer.prototype.joinValidation = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
iroha.Peer.startPeer = function(builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} publicKeyOffset
 */
iroha.Peer.addPublicKey = function(builder, publicKeyOffset) {
  builder.addFieldOffset(0, publicKeyOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} ipOffset
 */
iroha.Peer.addIp = function(builder, ipOffset) {
  builder.addFieldOffset(1, ipOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} trust
 */
iroha.Peer.addTrust = function(builder, trust) {
  builder.addFieldFloat64(2, trust, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} active
 */
iroha.Peer.addActive = function(builder, active) {
  builder.addFieldInt8(3, +active, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} joinNetwork
 */
iroha.Peer.addJoinNetwork = function(builder, joinNetwork) {
  builder.addFieldInt8(4, +joinNetwork, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} joinValidation
 */
iroha.Peer.addJoinValidation = function(builder, joinValidation) {
  builder.addFieldInt8(5, +joinValidation, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
iroha.Peer.endPeer = function(builder) {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // publicKey
  return offset;
};

/**
 *//////////////////////////////////
 *
 * @constructor
 */
iroha.Signature = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {iroha.Signature}
 */
iroha.Signature.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {iroha.Signature=} obj
 * @returns {iroha.Signature}
 */
iroha.Signature.getRootAsSignature = function(bb, obj) {
  return (obj || new iroha.Signature).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {iroha.PublicKey=} obj
 * @returns {iroha.PublicKey}
 */
iroha.Signature.prototype.publicKey = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new iroha.PublicKey).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {number} index
 * @returns {number}
 */
iroha.Signature.prototype.signature = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns {number}
 */
iroha.Signature.prototype.signatureLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint8Array}
 */
iroha.Signature.prototype.signatureArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @returns {flatbuffers.Long}
 */
iroha.Signature.prototype.timestamp = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
iroha.Signature.startSignature = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} publicKeyOffset
 */
iroha.Signature.addPublicKey = function(builder, publicKeyOffset) {
  builder.addFieldOffset(0, publicKeyOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} signatureOffset
 */
iroha.Signature.addSignature = function(builder, signatureOffset) {
  builder.addFieldOffset(1, signatureOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
iroha.Signature.createSignatureVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
iroha.Signature.startSignatureVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timestamp
 */
iroha.Signature.addTimestamp = function(builder, timestamp) {
  builder.addFieldInt64(2, timestamp, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
iroha.Signature.endSignature = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.iroha = iroha;
