[package]
name = "iroha_crypto_wasm"
version = "0.2.0"
authors = ["0x009922"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
# FIXME use upstream
iroha_crypto = { path = "../../../../iroha/crypto", default-features = false, features = [
    "rand",
] }

getrandom = { version = "0.2", features = ["js"] }

wasm-bindgen = "0.2.91"
serde = { version = "1", default-features = false, features = ["derive"] }
serde-wasm-bindgen = "0.6"
hex = { version = "0.4", default-features = false, features = ["alloc"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
serde_json = "1.0"
itertools = "0.12.1"
