/**
 * @packageDocumentation
 *
 * Iroha v2 data model codecs. Primarily contains the code generated by the `@scale-codec/definition-compiler`
 */

export * as datamodel from './datamodel'
export * as sugar from './sugar/index'
export * from '@scale-codec/definition-runtime'
