/**
 * @module @iroha2/data-model
 */
/**
 * @packageDocumentation
 *
 * Iroha v2 data model codecs. Primarily contains the code generated by the `@scale-codec/definition-compiler`
 */

export * as datamodel from './datamodel'
export * from './core'
export * from './ext'
