/**
 * @packageDocumentation
 *
 * Iroha v2 data model codecs. Primarily contains the code generated by the `@scale-codec/definition-compiler`
 */

export * from './generated';
export * from '@scale-codec/definition-runtime';
